#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v20
# autospec commit: a19cdc7
#
# Source0 file verified with key 0x356CE62C2B524099 (tom.hromatka@oracle.com)
#
Name     : libcgroup
Version  : 3.1.0
Release  : 25
URL      : https://github.com/libcgroup/libcgroup/releases/download/v3.1.0/libcgroup-3.1.0.tar.gz
Source0  : https://github.com/libcgroup/libcgroup/releases/download/v3.1.0/libcgroup-3.1.0.tar.gz
Source1  : https://github.com/libcgroup/libcgroup/releases/download/v3.1.0/libcgroup-3.1.0.tar.gz.asc
Source2  : 356CE62C2B524099.pkey
Summary  : Tools and libraries to control and monitor control groups
Group    : Development/Tools
License  : LGPL-2.0+
Requires: libcgroup-bin = %{version}-%{release}
Requires: libcgroup-lib = %{version}-%{release}
Requires: libcgroup-man = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : flex
BuildRequires : gnupg
BuildRequires : systemd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Control groups infrastructure. The tools and library help manipulate, control,
administrate and monitor control groups and the associated controllers.

%package bin
Summary: bin components for the libcgroup package.
Group: Binaries

%description bin
bin components for the libcgroup package.


%package dev
Summary: dev components for the libcgroup package.
Group: Development
Requires: libcgroup-lib = %{version}-%{release}
Requires: libcgroup-bin = %{version}-%{release}
Provides: libcgroup-devel = %{version}-%{release}
Requires: libcgroup = %{version}-%{release}

%description dev
dev components for the libcgroup package.


%package lib
Summary: lib components for the libcgroup package.
Group: Libraries

%description lib
lib components for the libcgroup package.


%package man
Summary: man components for the libcgroup package.
Group: Default

%description man
man components for the libcgroup package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 356CE62C2B524099' gpg.status
%setup -q -n libcgroup-3.1.0
cd %{_builddir}/libcgroup-3.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1728923721
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1728923721
rm -rf %{buildroot}
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cgclassify
/usr/bin/cgconfigparser
/usr/bin/cgcreate
/usr/bin/cgdelete
/usr/bin/cgexec
/usr/bin/cgget
/usr/bin/cgrulesengd
/usr/bin/cgset
/usr/bin/cgsnapshot
/usr/bin/cgxget
/usr/bin/cgxset
/usr/bin/libcgroup_systemd_idle_thread
/usr/bin/lscgroup
/usr/bin/lssubsys

%files dev
%defattr(-,root,root,-)
/usr/include/libcgroup.h
/usr/include/libcgroup/config.h
/usr/include/libcgroup/error.h
/usr/include/libcgroup/groups.h
/usr/include/libcgroup/init.h
/usr/include/libcgroup/iterators.h
/usr/include/libcgroup/log.h
/usr/include/libcgroup/systemd.h
/usr/include/libcgroup/tasks.h
/usr/include/libcgroup/tools.h
/usr/lib64/libcgroup.so
/usr/lib64/pkgconfig/libcgroup.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcgroup.so.3
/usr/lib64/libcgroup.so.3.1.0
/usr/lib64/security/pam_cgroup.so

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cgclassify.1
/usr/share/man/man1/cgcreate.1
/usr/share/man/man1/cgdelete.1
/usr/share/man/man1/cgexec.1
/usr/share/man/man1/cgget.1
/usr/share/man/man1/cgset.1
/usr/share/man/man1/cgsnapshot.1
/usr/share/man/man1/cgxget.1
/usr/share/man/man1/cgxset.1
/usr/share/man/man1/lscgroup.1
/usr/share/man/man1/lssubsys.1
/usr/share/man/man5/cgconfig.conf.5
/usr/share/man/man5/cgred.conf.5
/usr/share/man/man5/cgrules.conf.5
/usr/share/man/man8/cgconfigparser.8
/usr/share/man/man8/cgrulesengd.8
